def countNucFrequency(seq):
    tmpFreqDict = {
        "A": 0,
        "C": 0,
        "G": 0,
        "T": 0,
    }
    for nuc in seq:
        tmpFreqDict[nuc] += 1
    return tmpFreqDict

DNAString = "CCTCGCCGGTGTATCCATATCATCTATAGTAAGTGTAGGGGCCAAACGGATACGCTGTGGTCCCGAAGATTGTTTAGGGAAACGGCCCACAATTTAGTAATGGTGCGCTGTCTAAGATCAAGCGATCGGCACTTAACATAGCGAGACATTCGTGTAGGCAACGATCACTAAATATGTTGGTTGGGATATGCCCCACTGGAACGCCGATTCACGAGCCGGTTACATTGATCTGCGCTCTGAGTCTAGTCCTCGTGTTCACCTATAAGCACAGGCGATCACTGGACTCCATCGAGTCACTCGACCTCTGAATTTCAGCGGTATCCAATGCGGAGGGGATACGATGCAAACCAGACGTCCGATGTTGCACTGGCTCTCCACCCCCACGTCTATCTCGTGGGGATTACCCGGTGAGCACGGCGGTAATTCAGGAGCCTAATAGCTACGCCATTTCAGAGCGCTGACGGAGGAAAACAAGGATAAGGCCACGCGATAATACCTGATCTGGACGCGTAATACATGCGCAGCTCAATTGTGATTACTAACAAAAACACTCTTTGCAGGGTGACTATTTGAGAACGGAATGGCCAAAGGTAGATTTACCCGAATTGTGCACGCGGACAACCTGCTCGCTGGGATACGATTTTCTCCCCACGTTGGGTGACAGTTACCCCCAGCCAATTAACCGCCTCGGGAACCATAACGGACATAAGCTGGTTGTCTATATCCGGGCTCCCCGCCCTGCGTATCGGCGGGCACGCAGACTTGCAGCCGATTTACCTTCACTGCCAAGTCCATCTCGCAGCCAAATGTAATCAAGTGGCGAGAGCAATGATCTTTATAGTGATGGATTCTAGATACTACTCTCTATGCAGGTGGAAGCGCTCCGTG"
result = countNucFrequency(DNAString)

value_list = []
for key, val in result.items():
    value_list.append(str(val))
final_string = ' '.join(value_list)
print(final_string)